---
- name: Playbook
  hosts: centos
  become: yes

  vars:
    message1: Hi
    message2: World
    message3: Secret#laekfj@#$324

  tasks:
  - name: print secret variables
    debug:
      var: message3
  - name: print all messages
    debug:
      msg: "Secret was {{ message3 }}"
  - name: print server ovner
    debug:
      msg: "Server ovner is: {{ ovner }}"
  - name: Total string
    set_fact: full_message="{{ message1 }} {{ ovner }} from {{ message2 }} with secret {{ message3 }}"
  - name: Print total string
    debug:
      msg: "{{ full_message }}"
  - name: show OS version
    debug:
      var: ansible_os_family
  - name: Get uptime
    shell: uptime
    register: uptime_results
  - name: Show uptime
    debug:
      var: uptime_results.stdout


...
