---
- name: Install Apache web-server
  hosts: all
  become: yes

  vars:
    source_file: ./pub/html_css-master/
    dest: /var/www/html

  tasks:
  - name: Show linux version
    debug: var=ansible_os_family
  
  - block: # ansible_os_family == "RedHat"
    - name: Update CentOS repo
      yum: name=epel-release state=present

    - name: Install CentOS Apache web-server 
      yum: name=httpd state=present

    - name: Copy files to web-server
      copy: src={{ source_file }} dest={{ dest }} mode=0555
      notify: Restart CentOS web-server on changes in html directory

    - name: Start and enable Centos web-server
      service: name=httpd state=started enabled=yes

    when: ansible_os_family == "RedHat" 
    
  - block: # ansible_os_family == "Debian"
    - name: Update Ubuntu repo
      apt: name=update_cache=yes force_apt-get_yes cache_valid_time=3600 # cache_valid_time=seconds
    - name: Install Ubuntu Apache web-server
      apt: name=apache2 state=present

    - name: Copy files to web-server
      copy: src={{ source_file }} dest={{ dest }} mode=0555
      notify: Restart Ubuntu web-server on changes in html directory

    - name: Start and enable Ubuntu web-server
      service: name=apache2 state=started enabled=yes
    when: ansible_os_family == "Debian"

  handlers:
  - name: Restart CentOS web-server on changes in html directory
    service: name=httpd state=restarted
    when: ansible_os_family == "RedHat"

  - name: Restart Ubuntu web-server on changes in html directory
    service: name=apache2 state=restarted
    when: ansible_os_family == "Debian"   
...
