---
- name: Install web-server Apache on CentOS server
  hosts: centos
  become: yes

  tasks:
  - name: install httpd
    yum: name=httpd state=present
#    - name: httpd
#    - state: installed
  - name: enable httpd server on boot
    service: name=httpd state=started enabled=yes
#    - name: httpd
#  state: started
#  enabled: yes    

    #- name: Install web-server Apache on Ubuntu server
    #  hosts: ubuntu
    #  become: yes
    #
    #  tasks:  
    #  - name: install apache2
    #    apt:
    #    - name: apache2
    #    - state: installed
    #  - name: enable apache2 server on boot
    #    service:
    #    - name: apache2
    #      state: started
    #      enabled: yes  
...
