---
-  name: Loop playbook
   hosts: ubuntu
   become: yes
   
   tasks:
   - name: Print Hello to ALL
     debug: msg="Hello {{ item }}"
     loop:
      - "Vasya"
      - "Petya"
      - "Masha"
      - "Olya"
   - name: Example with loop until
     shell: echo -n Test >> test.txt && cat test.txt
     register: output
     delay: 2 # Delay in seconds
     retries: 10 # Default range is 10
     until: output.stdout.find("TestTestTestTest") == false
   
   - name: Print std output  
     debug:
       var: output.stdout

   - name: Install packages
     apt: name={{ item }} state=removed
     loop:
      - "python3"
#     - "tree"
      - "vim"
#      - "nginx"
#      - "mysql-client"
      
       
...  
