---
# Tasks file for deploy_apache
#
- block:
    - name: Install CentOS Apache web-server
      yum: name=httpd state=present
    - name: Enable web-server service
      service: name=httpd state=started enabled=yes
  when: ansible_os_family == "RedHat"

- block:
    - name: Install Ubuntu Apache web-server
      apt: name=apache2 state=present
    - name: Enable web-server service
      service: name=apache2 state=started enabled=yes
  when: ansible_os_family == "Debian"

- name: Copy source files to web-server
  copy: src={{ src_folder }} dest={{ dest_folder }}
  notify:
    - Restart CentOS web-server on changes in html directory
    - Restart Ubuntu web-server on changes in html directory
